### ISSUE TITLE
Wrong git-clone instructions on README!

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/SMPy#1]
Should be 

`git clone https://github.com/GeorgeVassilakis/SMPy.git`

**Comment by mcclearyj** [comment]
I will also add that in the `notebooks/testing.ipynb` example notebook, there is no such function as `utils.load_shear_data_test()`. I think that is supposed to be `utils.load_shear_data()`

**Comment by GeorgeVassilakis** [comment]
True, I encountered that error this morning while trying to load the data. Will fix!
