### ISSUE TITLE
Add B-mode maps

### ISSUE THREAD

**Issue by GeorgeVassilakis** [GeorgeVassilakis/SMPy#13]
Compute B mode maps alongside E mode (which is what we currently calculate). It can be a investigative tool of error.

**Comment by EdwardBerman** [comment]
This would be cool! For reference, the following may be useful: [Paper 1](https://watermark.silverchair.com/mnras0395-1265.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA4YwggOCBgkqhkiG9w0BBwagggNzMIIDbwIBADCCA2gGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM-ApPEXy0i9a51f0OAgEQgIIDOWIQ2lNEse3BzOQvMcjVJpon0L2b3Oks1fdZ7caD1R3t_7ZChtmOev99kpVX7bet0K02aNEsGTvLEaggkPdHTh5s_Y5Yn4IXCc2GFKwmtJF42d6SisJjlUOi_WBn7OcRMEpl_v6lnvR5bFStiBhTrH9xX7VmRcjZ9pZG7k8wnFms5VYouMUpsXe_kOIz9cVDYKAuriUXGf6ci8_HLZ4riZNE3VqJ8pS6EDV7mM-PTK-kloQ17w0A1si4RYp6RsbiH3a7KlFTEJafZi2S-PTm_fvrck5T4yXKo2--HarUel20cJg0H3czIPZORw5dPk_wN5DuWx-EahXCq8iFu-tzBCy-ZMyLDPnFKsw_ncI9dLB-ydQQRA2ErJJuRmrEoRXAGo8OtPlw4iTQSQ0wiobvo3TiiGLKO7Uet4hhlKwb3F73QgSOhS5BV-0g30okc6zoGPGdU1cA_yqXO765VEqHKB1xo3Szq6wNafCIK3zIeHaEjvfFNNededkQnmzPIO9unGokkLNvJEfxioQGtZEc9E0limgtg_FS0L2dJXwYo2SQGnslXgBTcSjjAIeFG8nmOGpkdsVNoEpR8Ve3CL-u4FoHs7qBoZ76GieS19hDwEnCzow2_8Pzx0iZgPMf1cTnIh9CURfeBsgSe2G1oUJqNS_C1Jno4IEA2cIvPweSVDAlphxOi7LypmU_jWUQ0qVxs-rsfxXXFf61Z9ckZjCauOfAN1pAO3deWSnjwWEq2fjAqWs0FZyhint4SvHcaNHxLBsyeXJMU9uzUoaZbmYbEwsdbUo7l5X7MfxwNCsmEyJxpMxrNKvgZml7Caa9-ygOQB_S52HIlMlWhaKM6rqCxcRTYD4qfe0H-sKY8psCnILqaGw6QHvUVgBpYgPa_UX9R0NO789Cz29oRIOx6yJpLtI4bytSAJ9se0TeC3cLuCGkqxEjNdOX2IdwdC6b6av5UpnKYTkLV7QtZVIcL_4Hh9Gsy_E5qAIC6DAwudpZvp8aEPPNaTqhloiWw-01-iHdd5PmM52wb1LNLeUbxjlwq4pHU2rYIDx0JVc-BXTXbrOU8KMVtlmH9pHdmMpPd_ZcjI8sB3Dij-pO1g) , [Paper 2](https://www.aanda.org/articles/aa/pdf/2020/06/aa36865-19.pdf) . Moreso the latter one, section 2,2.1 and eq 9. The implementation of KS+ may also be useful. @GeorgeVassilakis

**Comment by GeorgeVassilakis** [comment]
Sweet, thanks for the literature references @EdwardBerman. I'll check them out!
