### ISSUE TITLE
Create directory if not already exists

### ISSUE THREAD

**Issue by EdwardBerman** [GeorgeVassilakis/SMPy#16]
It would be useful if the directory for the fits output was created if it didn't already exist. For the example config to work, I had to first create a union_maps folder.

**Comment by GeorgeVassilakis** [comment]
Got it. I plan on doing a large restructuring of directories soon. Essentially an entire codebase reworking to ensure scalability and extensibility. I'm going to raise an issue for my restructuring but I will address your output directory wishes in my rebuild!
