### ISSUE TITLE
Coordinate Projection from Field Boundaries

### ISSUE THREAD

**Issue by GeorgeVassilakis** [GeorgeVassilakis/SMPy#18]
Field boundaries are currently approximated as a 2D rectangle. The boundaries and box size can and should be projected to a 3D celestial sphere.

**Comment by mcclearyj** [comment]
Relatedly, the default plotting function only plots a small subsection of the full image. Trying to expand the region leads to a funny aspect ratio that I can't seem to fix.

![MACSJ0723d3_7327_JWST_b_kmap2_Rinv](https://github.com/user-attachments/assets/483317b7-4741-4e4e-86d0-1af89ee3fe9d)
![MACSJ0723d3_7327_JWST_b_kmap0 75_Rinv](https://github.com/user-attachments/assets/1199f0dd-a25b-4427-b66a-d5894bfa2c94)

**Comment by mcclearyj** [comment]
At least part of the problem is probably that the declination range is a fraction of a degree, while the RA range is at least 1 degree. Whatever coordinate transformation is being made is clearly wrong!
