### ISSUE TITLE
WCS not being implemented correctly in final plot

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/SMPy#2]
The axes appear to be pointing in the wrong direction and/or the origin isn't being set correctly. The attached image shows a K-map superimposed on a DS9 image (with N pointing down to match the Python convention). There are a couple things going on here:

**Inconsistent origin**
- DS9 sets its origin at the bottom left to match the astronomical convention of "north up, east to the left." 
- Python, by default, sets the origin at the top left. This corresponds to north down, east to the left. 
- It's an easy fix in matplotlib: `origin = lower`

**Incorrect axis orientation**
- Second, and more annoyingly, the axes appear to be oriented incorrectly. 
- In the DS9 image, the top y-axis gridline is `-17.700`, but in SMPy, it's `-17.3`. 
- Conversely, the rightmost x-axis gridline is `130.700` in DS9,  but is `130.2` for SMPy.
- This might have something to do with the indexing. Python indexes into arrays as `(row, column) == (y, x)`, but the WCS is probably defined in terms of `(x, y) == (column, row)`.  
- This should probably be fixed; otherwise, comparisons between convergence maps and images get very confusing. 
- 
<img width="700" alt="Screenshot 2024-02-07 at 7 09 25 PM" src="https://github.com/GeorgeVassilakis/SMPy/assets/14120046/813381f7-31bd-490b-838d-5fa5196c6ec8">

**Comment by GeorgeVassilakis** [comment]
Thank you for catching these, I owe you a beer.

**Comment by mcclearyj** [comment]
Addressed with 16fa2ac37c81e2bb9d0c8a3227d70df82f76762b
