### ISSUE TITLE
Enhancement: save k-map as FITS file

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/SMPy#3]
It would be extremely useful to be able to save the convergence maps as FITS files with a WCS defined in the header for overplotting on coadd images in, e.g., DS9. I may make a fork and try implementing this myself!

**Comment by GeorgeVassilakis** [comment]
Great point and idea! Before you throw a lot of effort into a fork, I'll take a look at it this evening. I'd probably leave it as a parameter like "`export_fits = True/False`" and export it somehow that way. Will let you know!

**Comment by GeorgeVassilakis** [comment]
This is currently being addressed in a local branch I've created called `add-fits-export`. This theoretically works, but am waiting for testing from @mcclearyj before I push!

**Comment by GeorgeVassilakis** [comment]
This was addressed and implemented in Pull Request #12.
