### ISSUE TITLE
Move filtering elsewhere?

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/SMPy#5]
https://github.com/GeorgeVassilakis/SMPy/blob/e9d6f7e51a8167c2a00bf6cc3d8687a0d92d3a1a/SMPy/KaiserSquires/plot_kmap.py#L6

Future development may see the use of other smoothing kernels (some kind of wavelets approach, perhaps?). Moving the smoothing operation outside of the plotting function would make it easier to implement different smoothings.

**Comment by GeorgeVassilakis** [comment]
An output converge FITS file could have 1 layer be raw convergence, and another be the smoothed convergence in the same FITS file. Note this for development.
