### ISSUE TITLE
Increasing resolution parameter leads to weird kmap binning

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/SMPy#7]
Increasing the `resolution` parameter in the KSMap configuration file leads to images that seem to have the wrong bin size. The attached image was made using the parameters below. 

```
# Parameters
resolution: 1                    # Pixel resolution of the map in arcminutes
width: 110                       # Width of the map in pixels

```

For a 23 x 17 arcminute image, a resolution parameter of 1 should yield a 23 x 17 pixel image, but that's clearly not what gets produced! 
![MACSJ0723d3_7327_JWST_kmap](https://github.com/GeorgeVassilakis/SMPy/assets/14120046/3af4bebf-cec1-40d0-b02f-24111425b5e1)

**Comment by GeorgeVassilakis** [comment]
A mistake was made with the '`width`' parameter, where it wasn't adjusted accordingly when '`resolution`' was changed. The width of the image in pixels is equal to the field size (arcmin) / resolution (arcmin), so we update the code to calculate automatically.
